/* This file was generated by the "svnrev" utility.
 * You should not modify it manually, as it may be re-generated.
 *
 * $Revision: 3664$
 * $Date: 2006-11-08$
 */

#ifndef SVNREH_H
#define SVNREV_H

#define SVN_REV		3664
#define SVN_REVSTR	"3664"
#define SVN_REVDATE	"2006-11-08"
#define SVN_REVSTAMP	20061108L

#endif /* SVNREV_H */
